install.packages("ggplot2")
install.packages("dplyr")
install.packages("tidyr")
install.packages("gridExtra")
install.packages("maps")
install.packages("ggmap")
install.packages("ggsn")
install.packages("multcomp")
install.packages("lme4")
install.packages("vegan")

library("ggplot2")
library("dplyr")
library("tidyr")
library("gridExtra")
library("maps")
library("ggmap")
library("ggsn")
library("multcomp")
library("lme4")
library("vegan")

setwd("c:/Users/endrem/Documents/R-kurs")
getws()